-- MOSTRAR TODOS LOS REGISTROS DE LA TABLA MOVIES
SELECT * FROM MOVIES;

-- MOSTRAR EL NOMBRE, APELLIDO Y RATING DE TODOS LOS ACTORES
SELECT CONCAT(first_name, ' ', last_name) "FNombre Completo", rating "Rating" FROM actors;

-- MOSTRAR EL TÍTULO DE TODAS LAS SERIES Y USAR ALIAS PARA QUE TANTO EL NOMBRE DE LA TABLA
-- COMO EL CAMPO ESTÉN EN ESPAÑOL
SELECT title "Titulo" FROM series Series_de_TV;

-- MOSTRAR EL NOMBRE Y APELLIDO DE LOS ACTORES CUYO RATING SEA MAYOR A 7.5
SELECT CONCAT(first_name, ' ', last_name) "Nombre Completo", rating "Rating" FROM actors WHERE rating > 7.5;

-- MOSTRAR EL TITULO DE LAS PELÍCULAS, EL RATING Y LOS PREMIOS DE LAS PELÍCULAS
-- CON UN RATING MAYOR A 7.5 Y CON MÁS DE DOS PREMIOS
SELECT title "Titulo", rating "Rating", awards "Premios" FROM movies
WHERE rating > 7.5 AND awards > 2;

-- MOSTRAR EL TÍTULO DE LAS PELÍCULAS Y EL RATING ORDENADAS POR RATING EN FORMA ASCENDENTE
SELECT title "Titulo", rating "Rating" FROM movies
ORDER BY rating ASC;

-- MOSTRAR LOS TÍTULOS DE LAS PRIMERAS TRES PELÍCULAS EN LA BASE DE DATOS
SELECT title "Titulo" FROM movies LIMIT 3;

-- MOSTRAR EL TOP 5 DE LAS PELÍCULAS CON MAYOR RATING
SELECT title "Titulo", rating "Rating" FROM MOVIES ORDER BY rating DESC LIMIT 3;

-- LISTAR LOS PRIMEROS 10 ACTORES
SELECT CONCAT(first_name, ' ', last_name) "Nombre Completo" FROM actors LIMIT 10;

-- MOSTRAR EL TÍTULO Y RATING DE TODAS LAS PELÍCULAS CUYO TÍTULO SEA DE TOY STORY
SELECT title "Titulo" FROM movies WHERE title LIKE "Toy Story%";

-- MOSTRAR TODOS LOS ACTORES CUYOS NOMBRES EMPIEZAN CON SAM
SELECT CONCAT(first_name, ' ', last_name) "Nombre Completo" FROM actors WHERE first_name LIKE "Sam%";

-- MOSTRAR EL TÍTULO DE LAS PELICULAS QUE SALIERON ENTRE EL 2004 Y 2008
SELECT title "Titulo" FROM movies WHERE YEAR(release_date) BETWEEN 2004 AND 2008;

-- TRAER EL TÍTULO DE LAS PELÍCULAS CON EL RATING MAYOR A 3, CON MÁS DE 1 PREMIO Y CON FECHA DE LANZAMIENTO ENTRE
-- EL AÑO 1988 AL 2009. ORDENAR LOS RESULTADOS POR RATING
SELECT title "Titulo" FROM movies WHERE YEAR(release_date) BETWEEN 1988 AND 2009
ORDER BY rating;





