-- MySQL Script generated by MySQL Workbench
-- Fri Jan 20 10:04:04 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema empleados
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema empleados
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `empleados` DEFAULT CHARACTER SET utf8 ;
USE `empleados` ;

-- -----------------------------------------------------
-- Table `empleados`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empleados`.`departamento` (
  `depto_nro` VARCHAR(45) NOT NULL,
  `nombre_depto` VARCHAR(45) NOT NULL,
  `localidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`depto_nro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empleados`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empleados`.`empleado` (
  `cod_empleado` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `puesto` VARCHAR(45) NOT NULL,
  `fecha_alta` DATETIME NOT NULL,
  `salario` DECIMAL(10) NOT NULL,
  `comision` DECIMAL(10) NULL,
  `depto_nro` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_empleado`),
  INDEX `fk_empleado_departamento_idx` (`depto_nro` ASC) VISIBLE,
  CONSTRAINT `fk_empleado_departamento`
    FOREIGN KEY (`depto_nro`)
    REFERENCES `empleados`.`departamento` (`depto_nro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `empleados` ;

-- -----------------------------------------------------
-- Placeholder table for view `empleados`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empleados`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `empleados`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empleados`.`view1`;
USE `empleados`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
