-- MySQL Script generated by MySQL Workbench
-- Fri Jan 20 09:32:13 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`libro` (
  `id_libro` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `editorial` VARCHAR(45) NULL,
  `area` VARCHAR(45) NULL,
  PRIMARY KEY (`id_libro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`autor` (
  `id_autor` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `nacionalidad` VARCHAR(45) NULL,
  PRIMARY KEY (`id_autor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estudiante` (
  `id_lector` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `carrera` VARCHAR(45) NULL,
  `edad` INT NULL,
  PRIMARY KEY (`id_lector`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prestamo` (
  `fecha_prestamo` DATETIME NOT NULL,
  `fecha_devolucion` DATETIME NULL,
  `devuelto` TINYINT(1) NULL,
  `id_libro` INT NOT NULL,
  `id_lector` INT NOT NULL,
  INDEX `fk_prestamo_libro1_idx` (`id_libro` ASC) VISIBLE,
  INDEX `fk_prestamo_estudiante1_idx` (`id_lector` ASC) VISIBLE,
  PRIMARY KEY (`fecha_prestamo`),
  CONSTRAINT `fk_prestamo_libro1`
    FOREIGN KEY (`id_libro`)
    REFERENCES `mydb`.`libro` (`id_libro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prestamo_estudiante1`
    FOREIGN KEY (`id_lector`)
    REFERENCES `mydb`.`estudiante` (`id_lector`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`libro_autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`libro_autor` (
  `libro_id_libro` INT NOT NULL,
  `autor_id_autor` INT NOT NULL,
  PRIMARY KEY (`libro_id_libro`, `autor_id_autor`),
  INDEX `fk_libro_has_autor_autor1_idx` (`autor_id_autor` ASC) VISIBLE,
  INDEX `fk_libro_has_autor_libro_idx` (`libro_id_libro` ASC) VISIBLE,
  CONSTRAINT `fk_libro_has_autor_libro`
    FOREIGN KEY (`libro_id_libro`)
    REFERENCES `mydb`.`libro` (`id_libro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_libro_has_autor_autor1`
    FOREIGN KEY (`autor_id_autor`)
    REFERENCES `mydb`.`autor` (`id_autor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
